### ISSUE TITLE
Default pullquote needs styling

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#160] opened 2019-11-16 03:19 UTC
From: http://backtobasics.c4aa.org/training/

Solid color looks like this:

<img width="611" alt="Screen Shot 2019-11-15 at 10 18 21 PM" src="https://user-images.githubusercontent.com/67271/68987236-f65ea080-07f5-11ea-8f48-527da94dfe6a.png">

Default looks like this:

<img width="630" alt="Screen Shot 2019-11-15 at 10 18 34 PM" src="https://user-images.githubusercontent.com/67271/68987237-f6f73700-07f5-11ea-91f2-fb551cbbeab9.png">

**Comment by slambert** [comment] 2021-12-21 18:42
Not sure "is solid color" still is available. See https://github.com/thec4aa/c4aa-org/issues/229 - I think gutenberg has changed to letting you select the background and foreground colors for Pullquote Blocks. Which is cool, but left this code behind!

**Comment by slambert** [comment] 2023-03-26 18:34
Worth testing whether or not gutenburg changes this.

**Comment by andrewheins** [comment] 2023-08-14 21:47
Closing as a duplicate of #229

**Closed by andrewheins** 2023-08-14 21:47 UTC
Labels: bug, css-only
