### ISSUE TITLE
Extra menu item doesn't flow well

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#209] opened 2021-04-23 14:11 UTC
We added a "Press" menu item and it's not flowing as well as the other menu items:

![Screen Shot 2021-04-23 at 10 09 34 AM](https://user-images.githubusercontent.com/67271/115883775-2dd67100-a41c-11eb-884d-33b71ecc18bb.png)

See also #190

**Comment by slambert** [comment] 2021-09-20 14:22
We could do submenus. Or remove it and add press to the About page?

**Comment by andrewheins** [comment] 2023-04-27 15:13
If we were to implement dropdowns, this might alleviate the squish issue, as we could nest it under "News". Alternatively, we can look at updating the styling such that it never wraps.

**Comment by slambert** [comment] 2023-08-12 00:16
I think the staff want drop downs. But they have this idea that they'll pack the menu with all kinds of stuff. But when looking at the heatmap of how people use the menu, on the home page at least, they mainly just click on "What We Do".

@andrewheins Did I get you into Matomo Stats?

**Comment by andrewheins** [comment] 2023-08-14 21:46
@slambert Some of that could be design, some could be wording of the nav, some could be how users prioritize your content.

And yes, I'm in Matomo Stats.

I'm going to close this as a close duplicate of #240, but we can address this separately if need be once that's resolved.

**Closed by andrewheins** 2023-08-14 21:46 UTC
